[package]
name = "lattice-node"
version = "0.1.0"
edition = "2024"

[dependencies]
lattice-ipc = { path = "../lattice-ipc" }
lattice-protocol = { path = "../lattice-protocol" }
serde_json = "1"
sysinfo = "0.38.4"
tokio = { version = "1", features = ["fs", "io-util", "macros", "net", "process", "rt-multi-thread", "signal", "sync", "time"] }
